---
version: 2
updates:
- package-ecosystem: gomod
  open-pull-requests-limit: 1
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: k8s.io/*
  - dependency-name: knative.dev/*
  allow:
  - dependency-type: "all"
- package-ecosystem: github-actions
  open-pull-requests-limit: 1
  directory: /
  schedule:
    interval: weekly
